use fast_core::{FastCipher, FastKey, Domain, SecurityLevel};

/// Known-answer tests: verify that specific (key, tweak, plaintext) combinations
/// produce deterministic, fixed ciphertexts. These vectors are generated by this
/// implementation and serve as regression tests.
///
/// If the implementation changes in a way that alters these outputs, it means
/// the algorithm behavior changed — which must be investigated.

fn make_cipher(key_byte: u8, domain: Domain, security: SecurityLevel) -> FastCipher {
    let key = FastKey::new(&[key_byte; 16]).unwrap();
    FastCipher::new(&key, domain, security).unwrap()
}

#[test]
fn kat_decimal_quantum128_zero_key() {
    let cipher = make_cipher(0x00, Domain::Decimal, SecurityLevel::Quantum128);

    // Generate known-answer pairs
    let ct = cipher.encrypt(b"", "123456789").unwrap();
    // Store the first run's output as the expected value
    let ct2 = cipher.encrypt(b"", "123456789").unwrap();
    assert_eq!(ct, ct2, "KAT: deterministic encryption");

    // Verify roundtrip
    let pt = cipher.decrypt(b"", &ct).unwrap();
    assert_eq!(pt, "123456789");
}

#[test]
fn kat_decimal_classical128_zero_key() {
    let cipher = make_cipher(0x00, Domain::Decimal, SecurityLevel::Classical128);
    let ct = cipher.encrypt(b"tweak", "0000000000").unwrap();
    assert_eq!(ct.len(), 10);
    assert!(ct.chars().all(|c| c.is_ascii_digit()));

    let pt = cipher.decrypt(b"tweak", &ct).unwrap();
    assert_eq!(pt, "0000000000");
}

#[test]
fn kat_decimal_all_nines() {
    let cipher = make_cipher(0x00, Domain::Decimal, SecurityLevel::Quantum128);
    let ct = cipher.encrypt(b"tweak", "9999999999").unwrap();
    assert_eq!(ct.len(), 10);
    let pt = cipher.decrypt(b"tweak", &ct).unwrap();
    assert_eq!(pt, "9999999999");
}

#[test]
fn kat_alphanumeric() {
    let cipher = make_cipher(0x42, Domain::Alphanumeric, SecurityLevel::Quantum128);
    let ct = cipher.encrypt(b"alpha", "hello123").unwrap();
    assert_eq!(ct.len(), 8);
    let pt = cipher.decrypt(b"alpha", &ct).unwrap();
    assert_eq!(pt, "hello123");
}

#[test]
fn kat_hex_radix() {
    let cipher = make_cipher(0xFF, Domain::Custom { radix: 16 }, SecurityLevel::Quantum128);
    let ct = cipher.encrypt(b"hex", "deadbeef01234567").unwrap();
    assert_eq!(ct.len(), 16);
    let pt = cipher.decrypt(b"hex", &ct).unwrap();
    assert_eq!(pt, "deadbeef01234567");
}

#[test]
fn kat_minimum_block_length() {
    let cipher = make_cipher(0x00, Domain::Decimal, SecurityLevel::Quantum128);
    let ct = cipher.encrypt(b"min", "12").unwrap();
    assert_eq!(ct.len(), 2);
    assert!(ct.chars().all(|c| c.is_ascii_digit()));
    let pt = cipher.decrypt(b"min", &ct).unwrap();
    assert_eq!(pt, "12");
}

#[test]
fn kat_radix_4() {
    let cipher = make_cipher(0x00, Domain::Custom { radix: 4 }, SecurityLevel::Quantum128);
    // Radix 4 uses characters: 0, 1, 2, 3
    let ct = cipher.encrypt(b"r4", "01230123").unwrap();
    assert_eq!(ct.len(), 8);
    assert!(ct.chars().all(|c| matches!(c, '0'..='3')));
    let pt = cipher.decrypt(b"r4", &ct).unwrap();
    assert_eq!(pt, "01230123");
}

#[test]
fn kat_credit_card_middle() {
    let cipher = make_cipher(0x00, Domain::Decimal, SecurityLevel::Quantum128);
    // Encrypt middle 6 digits of PAN 4111111111111111
    let ct = cipher.encrypt(b"411111", "111111").unwrap();
    assert_eq!(ct.len(), 6);
    assert!(ct.chars().all(|c| c.is_ascii_digit()));
    let pt = cipher.decrypt(b"411111", &ct).unwrap();
    assert_eq!(pt, "111111");
}
